#!/bin/sh

# You may copy this file, but moving it causes problems.

# Source directory
src="./"
cd $src;

# Prints a message with a new line at end
printfl () {
    printf "$1\n"
}

# Helps path
help="src/help.php"

# Errors while entering commands
moreInfo="Try 'dej --help' for more information."

commandExpectedError=\
"You must specify a command.
$moreInfo"

badUsageError=\
"Bad usage.
$moreInfo"

unknownCommandError=\
"Unknown command
$moreInfo"

tooManyArgsError=\
"Too many arguments supplied!
$moreInfo"

# No arguments supplied
if [ $# -eq 0 ]; then
    printfl "$commandExpectedError"

# An arguments supplied
elif [ $# -eq 1 ]; then
    case $1 in
        # Start PHP process for each command
        start|stop|status|restart)
            sh src/php.sh $1
            ;;
        help|-h|--help)
            php $help "help";
            ;;
        config|users)
            printfl "$badUsageError"
            ;;
        *)
            printfl "$unknownCommandError"
            ;;
    esac

# Two arguments supplied
elif [ $# -eq 2 ]; then
    case $1 in
        # User wants help on specific command
        help|-h|--help)
            php $help $2
            ;;
        config)
            case $2 in
                # User wants a list of available fields
                list)
                    php $help "config_list"
                    ;;
                # User wants to create the configuration file
                create|check)
                    sh src/php.sh $2
                    ;;
                *)
                    printfl "$badUsageError"
                    ;;
            esac
            ;;
        start|stop|restart|status)
            printfl "$badUsageError"
            ;;
        *)
            printfl "$unknownCommandError"
            ;;
    esac

# Three arguments supplied
elif [ $# -eq 3 ]; then
    case $1 in
        --help|start|stop|restart|status)
            printfl "$badUsageError"
            ;;
        # Change the configuration file (i.e. config/data.json)
        config)
            sh src/php.sh config $2 $3
            ;;
        *)
            printfl "$unknownCommandError"
            ;;
    esac

# Too many arguments (> 3)
else
    printfl "$tooManyArgsError"
fi